/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.prog4.evaluacion.vista;

import co.edu.utp.isc.prog4.evaluacion.controlador.ProfesorControlador;
import co.edu.utp.isc.prog4.evaluacion.modelo.Prueba;
import co.edu.utp.isc.prog4.evaluacion.patrones.PrincipalVisitador;
import co.edu.utp.isc.prog4.evaluacion.patrones.ProfesorVisitador;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author utp
 */
public class PnlProfesor extends javax.swing.JPanel implements ProfesorVisitador {

    /**
     * Creates new form Profesor
     */
    public PnlProfesor() {
        initComponents();
        pnlProfesorPrueba1.setVisitador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnNuevaPrueba = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPruebas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnEliminarPrueba = new javax.swing.JButton();
        pnlTarjetas = new javax.swing.JPanel();
        pnlProfesorPrueba1 = new co.edu.utp.isc.prog4.evaluacion.vista.PnlProfesorPrueba();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplicacion del Profesor");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(200);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnNuevaPrueba.setText("Nuevo");
        btnNuevaPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPruebaActionPerformed(evt);
            }
        });
        jPanel5.add(btnNuevaPrueba);

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pruebas"));

        tblPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Materia", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPruebasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPruebas);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnEliminarPrueba.setText("Eliminar");
        btnEliminarPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPruebaActionPerformed(evt);
            }
        });
        jPanel6.add(btnEliminarPrueba);

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(jPanel1);

        pnlTarjetas.setLayout(new java.awt.CardLayout());
        pnlTarjetas.add(pnlProfesorPrueba1, "card2");

        jSplitPane1.setRightComponent(pnlTarjetas);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        visitador.cambiarTarjeta("inicio");
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEliminarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPruebaActionPerformed
        if (tblPruebas.getSelectedRowCount() == 1
                && JOptionPane.showConfirmDialog(this, "Esta seguro en eliminar?") == JOptionPane.YES_OPTION) {
            int row = tblPruebas.getSelectedRow();
            try {
                ProfesorControlador.getInstance().eliminarPrueba((Long) tblPruebas.getValueAt(row, 0));
                JOptionPane.showMessageDialog(this, "Prueba eliminada");
                cargarTablaPruebas();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Prueba no puede ser eliminada");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEliminarPruebaActionPerformed

    private void btnNuevaPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPruebaActionPerformed
        pnlProfesorPrueba1.limpiarCampos();
    }//GEN-LAST:event_btnNuevaPruebaActionPerformed

    private void tblPruebasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPruebasMouseReleased
        // TODO add your handling code here:
        if(evt.getClickCount() > 2){
            int row = tblPruebas.getSelectedRow();
            pnlProfesorPrueba1.cargarPrueba((Long) tblPruebas.getValueAt(row, 0));
        }
    }//GEN-LAST:event_tblPruebasMouseReleased

    public void setVisitador(PrincipalVisitador visitador) {
        this.visitador = visitador;
        cargarTablaPruebas();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminarPrueba;
    private javax.swing.JButton btnNuevaPrueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private co.edu.utp.isc.prog4.evaluacion.vista.PnlProfesorPrueba pnlProfesorPrueba1;
    private javax.swing.JPanel pnlTarjetas;
    private javax.swing.JTable tblPruebas;
    // End of variables declaration//GEN-END:variables
    private PrincipalVisitador visitador;

    @Override
    public void cargarTablaPruebas() {
        List<Prueba> pruebas = ProfesorControlador.getInstance().listarPruebas();

        // Borro los datos existentes de la tabla
        while (tblPruebas.getRowCount() > 0) {
            ((DefaultTableModel) tblPruebas.getModel()).removeRow(0);
        }

        // Agrego los datos que fueron consultados
        for (Prueba prueba : pruebas) {
            ((DefaultTableModel) tblPruebas.getModel()).addRow(new Object[]{
                prueba.getId(),
                prueba.getMateria(),
                prueba.getNombre()
            });
        }
    }
}
