/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.prog4.evaluacion.vista;

import co.edu.utp.isc.prog4.evaluacion.patrones.PrincipalVisitador;

/**
 *
 * @author utp
 */
public class PnlProfesor extends javax.swing.JPanel {

    /**
     * Creates new form Profesor
     */
    public PnlProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnNuevaPrueba = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPruebas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pnlTarjetas = new javax.swing.JPanel();
        pnlProfesorPrueba1 = new co.edu.utp.isc.prog4.evaluacion.vista.PnlProfesorPrueba();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplicacion del Profesor");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(200);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnNuevaPrueba.setText("Nuevo");
        jPanel5.add(btnNuevaPrueba);

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pruebas"));

        tblPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Materia", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPruebas);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton2.setText("Eliminar");
        jPanel6.add(jButton2);

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(jPanel1);

        pnlTarjetas.setLayout(new java.awt.CardLayout());
        pnlTarjetas.add(pnlProfesorPrueba1, "card2");

        jSplitPane1.setRightComponent(pnlTarjetas);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        visitador.cambiarTarjeta("inicio");
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    public void setVisitador(PrincipalVisitador visitador) {
        this.visitador = visitador;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnNuevaPrueba;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private co.edu.utp.isc.prog4.evaluacion.vista.PnlProfesorPrueba pnlProfesorPrueba1;
    private javax.swing.JPanel pnlTarjetas;
    private javax.swing.JTable tblPruebas;
    // End of variables declaration//GEN-END:variables
    private PrincipalVisitador visitador;
}
